travis:
  secure:
    BINSTAR_TOKEN: TYWmmJKgAUD6WnvpI/ka1upZE8b5xDXVw357Ul3JyWJeXkT7GDPf1Vq2uAse+yZVTLQv55RpBLqqxBK2fzTV2u7WJHjs8Bf3QcQ4JEhx2G3Uy1H+8U7rpDvJcy/mIWeVjM8Go2ny+7mlwCYesn/UDvi/pGLUoGAQc2JZ0yjhi7sJhPrGZGG6nIcLzAfTfzF9pqmT18vBK2VG8UfrBThtquNxMbZsu/i+g5XB7z8zpyH3RHtjYGky+3OPpHzG1hJm49EhzovyaN+314kFpjyNGNmxoYhql8rFXV5NP5Vgy8OhgsaNHAC2w3L79yRJClgi+i1OZ1mMZahtYO1oGx5idemDp2As/btQZ6ZjsfHeAxcTala9WeJCjCpe6QOgeCLRjwT8u/vXhzBDEGdEZ+TpL3Vc1B0M0Kui6Ahw2jSwznUz8YLR90dExDOUeyaHkbGNTuWz/CkLydQqQjDXQEicbA/fpIGYeg8ER8i/q4qP7wa3Y137gOJhsYNBQrTG2Ri/zV+HJUo7h86+9Voi+5dq/ft+2MkNadKHzPNu1o+ZMWX5LzG4+ssFtL3ggPjY2THUR8qUtCtQiiTdMQrUZulFGjVj1fInXUKHyifVB4btDQWj6CBSNX/pHKi21mTGvjtZM6V67eAEitfXYRLeoHOJVRT4PAm+rNBoujwvNnSyJqM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
